# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

WORKDIR /app

COPY . .

# Set environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD lucie
ENV POSTGRES_DB postgres

# Expose PostgreSQL port
EXPOSE 5432
