version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lucie
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mf_network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]

  load_forecast:
    build:
      context: load/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mf_network

  api_forecast:
    build:
      context: api/
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - mf_network

  front_forecast:
    build:
      context: front/
    ports:
      - "8001:8001"
    networks:
      - mf_network

networks:
  mf_network:
    driver: bridge
